name: GitGuardian Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    name: Secret Scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ggshield
        run: pip install ggshield

      - name: Scan code for secrets
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        run: ggshield secret scan repo .
